# -*- coding: utf-8 -*-
"""scis_raie_dairy_main_stable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QXydAU4RLCY2fXGGagPKnC0EI0AsB3Zz
"""

# ==============================================================
# SCIS-RAIE Dairy Viability Lab
# Version 1.0
# Author: Andrés Polo Roa
# Year: 2026
# ==============================================================

import pyomo.environ as pyo
print(pyo.SolverFactory("highs").available(exception_flag=False))

print("highs:", pyo.SolverFactory("highs").available(exception_flag=False))
print("glpk:", pyo.SolverFactory("glpk").available(exception_flag=False))

from __future__ import annotations

import json
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Dict, Optional, Tuple

import numpy as np
import pandas as pd
import pyomo.environ as pyo


@dataclass
class SoftwareMetadata:
    software_name: str = "SCIS-RAIE Dairy Viability Lab"
    version: str = "1.0.0-pre-registry"
    authors: str = "Andrés Polo Roa et al."
    owner: str = "To be defined by institution"
    description: str = (
        "Decision-support prototype for viability and resilience analysis "
        "in dairy supply chains under severe disruption scenarios."
    )


@dataclass
class ScenarioConfig:
    name: str
    demand_factor: float
    production_factor: float
    transport_factor: float
    adaptive_cost_factor: float
    recovery_target: float


@dataclass
class BenchmarkReference:
    FO: Optional[float] = None
    CVaR: Optional[float] = None
    Vtot: Optional[float] = None
    TTR: Optional[float] = None
    SL_agg: Optional[float] = None
    ShortAgg: Optional[float] = None
    Cadapt: Optional[float] = None
    RecoveryEfficiency: Optional[float] = None


class DairyCaseData:
    def __init__(self) -> None:
        self.plants = ["j1", "j2", "j3"]
        self.cdc = ["k1", "k2", "k3", "k4"]
        self.markets = ["n1", "n2", "n3"]
        self.products = ["mantequilla", "yogurt", "leche_past"]
        self.weeks = [1, 2, 3, 4, 5, 6, 7, 8]
        self.base_scenarios = self._build_default_scenarios()

        base_product_demand = {
            "mantequilla": 700.0,
            "yogurt": 8000.0,
            "leche_past": 11500.0,
        }
        market_factor = {"n1": 1.00, "n2": 1.03, "n3": 0.97}
        week_factor = {
            1: 0.95, 2: 0.98, 3: 1.00, 4: 1.02,
            5: 1.05, 6: 1.03, 7: 1.00, 8: 1.01
        }

        self.demand = {
            (pr, mk, t): base_product_demand[pr] * market_factor[mk] * week_factor[t]
            for pr in self.products
            for mk in self.markets
            for t in self.weeks
        }

        plant_factor = {"j1": 0.85, "j2": 1.05, "j3": 0.95}
        base_capacity = {
            "mantequilla": 1700.0,
            "yogurt": 9000.0,
            "leche_past": 14000.0,
        }
        self.capacity = {
            (pl, pr, t): base_capacity[pr] * plant_factor[pl]
            for pl in self.plants
            for pr in self.products
            for t in self.weeks
        }

        self.prod_cost = {
            "mantequilla": 12.0,
            "yogurt": 9.0,
            "leche_past": 8.0,
        }
        self.extra_cost = {
            "mantequilla": 15.0,
            "yogurt": 11.0,
            "leche_past": 10.0,
        }
        self.subcontract_cost = {
            "mantequilla": 18.0,
            "yogurt": 14.0,
            "leche_past": 13.0,
        }
        self.shortage_cost = {
            "mantequilla": 45.0,
            "yogurt": 35.0,
            "leche_past": 38.0,
        }

        self.transport_cost_pc = 1.40
        self.transport_cost_cm = 1.10
        self.reconfig_cost = 3.50

        self.initial_cd_inventory = {
            (k, pr): 0.0
            for k in self.cdc
            for pr in self.products
        }

        self.benchmark = {
            "s1": BenchmarkReference(
                FO=-2.15998e9,
                Vtot=0.309,
                TTR=6.0,
                SL_agg=0.309,
                ShortAgg=355494.231,
                Cadapt=26445.595,
                RecoveryEfficiency=1.168496e-5,
            ),
            "s2": BenchmarkReference(
                Vtot=0.327,
                TTR=5.0,
                SL_agg=0.327,
                ShortAgg=321677.607,
                Cadapt=31567.722,
                RecoveryEfficiency=1.036878e-5,
            ),
            "s3": BenchmarkReference(
                Vtot=0.475,
                TTR=4.0,
                SL_agg=0.475,
                ShortAgg=250918.710,
                Cadapt=37121.152,
                RecoveryEfficiency=1.279593e-5,
            ),
            "s4": BenchmarkReference(
                Vtot=0.478,
                TTR=4.0,
                SL_agg=0.478,
                ShortAgg=243796.525,
                Cadapt=14918.392,
                RecoveryEfficiency=3.202393e-5,
            ),
            "s5": BenchmarkReference(
                Vtot=0.222,
                TTR=6.0,
                SL_agg=0.222,
                ShortAgg=463026.194,
                Cadapt=23838.609,
                RecoveryEfficiency=9.321401e-6,
            ),
        }

    @staticmethod
    def _build_default_scenarios() -> Dict[str, ScenarioConfig]:
        return {
            "s1": ScenarioConfig("s1", 1.35, 0.78, 0.85, 1.10, 6.0),
            "s2": ScenarioConfig("s2", 1.22, 0.82, 0.92, 1.15, 5.0),
            "s3": ScenarioConfig("s3", 1.10, 0.92, 0.95, 1.25, 4.0),
            "s4": ScenarioConfig("s4", 1.08, 0.96, 0.98, 0.95, 4.0),
            "s5": ScenarioConfig("s5", 1.45, 0.70, 0.80, 1.05, 6.0),
        }


class SCISRAIEDairyLab:
    def __init__(
        self,
        data: Optional[DairyCaseData] = None,
        metadata: Optional[SoftwareMetadata] = None,
        working_dir: str | Path = ".",
    ) -> None:
        self.data = data or DairyCaseData()
        self.metadata = metadata or SoftwareMetadata()
        self.working_dir = Path(working_dir)
        self.working_dir.mkdir(parents=True, exist_ok=True)

        self.model: Optional[pyo.ConcreteModel] = None
        self.solver_name_used: Optional[str] = None
        self.kpi_summary: Dict[str, float] = {}
        self.kpi_by_scenario: pd.DataFrame = pd.DataFrame()
        self.validation_table: pd.DataFrame = pd.DataFrame()

    def build_model(self) -> pyo.ConcreteModel:
        d = self.data
        m = pyo.ConcreteModel(name=self.metadata.software_name)

        m.P = pyo.Set(initialize=d.plants)
        m.K = pyo.Set(initialize=d.cdc)
        m.M = pyo.Set(initialize=d.markets)
        m.PR = pyo.Set(initialize=d.products)
        m.T = pyo.Set(initialize=d.weeks, ordered=True)
        m.S = pyo.Set(initialize=list(d.base_scenarios.keys()))

        m.demand = pyo.Param(
            m.PR, m.M, m.T,
            initialize=lambda _m, pr, mk, t: d.demand[(pr, mk, t)],
            within=pyo.NonNegativeReals
        )

        m.capacity = pyo.Param(
            m.P, m.PR, m.T,
            initialize=lambda _m, p, pr, t: d.capacity[(p, pr, t)],
            within=pyo.NonNegativeReals
        )

        m.prod_cost = pyo.Param(
            m.PR, initialize=lambda _m, pr: d.prod_cost[pr], within=pyo.NonNegativeReals
        )
        m.extra_cost = pyo.Param(
            m.PR, initialize=lambda _m, pr: d.extra_cost[pr], within=pyo.NonNegativeReals
        )
        m.subcontract_cost = pyo.Param(
            m.PR, initialize=lambda _m, pr: d.subcontract_cost[pr], within=pyo.NonNegativeReals
        )
        m.short_cost = pyo.Param(
            m.PR, initialize=lambda _m, pr: d.shortage_cost[pr], within=pyo.NonNegativeReals
        )

        m.dem_factor = pyo.Param(
            m.S,
            initialize=lambda _m, s: d.base_scenarios[s].demand_factor,
            within=pyo.NonNegativeReals
        )
        m.prod_factor = pyo.Param(
            m.S,
            initialize=lambda _m, s: d.base_scenarios[s].production_factor,
            within=pyo.NonNegativeReals
        )
        m.adapt_factor = pyo.Param(
            m.S,
            initialize=lambda _m, s: d.base_scenarios[s].adaptive_cost_factor,
            within=pyo.NonNegativeReals
        )

        m.XR = pyo.Var(m.P, m.PR, m.T, m.S, domain=pyo.NonNegativeReals)
        m.XE = pyo.Var(m.P, m.PR, m.T, m.S, domain=pyo.NonNegativeReals)
        m.XS = pyo.Var(m.P, m.PR, m.T, m.S, domain=pyo.NonNegativeReals)

        m.FlowPK = pyo.Var(m.P, m.K, m.PR, m.T, m.S, domain=pyo.NonNegativeReals)
        m.FlowKM = pyo.Var(m.K, m.M, m.PR, m.T, m.S, domain=pyo.NonNegativeReals)

        m.InvCD = pyo.Var(m.K, m.PR, m.T, m.S, domain=pyo.NonNegativeReals)
        m.ShortDem = pyo.Var(m.PR, m.M, m.T, m.S, domain=pyo.NonNegativeReals)

        m.ViolY = pyo.Var(m.T, m.S, domain=pyo.NonNegativeReals)
        m.zInn = pyo.Var(m.T, m.S, bounds=(0.0, 1.0))
        m.Mmem = pyo.Var(m.T, m.S, bounds=(0.0, 1.0))
        m.Cadapt = pyo.Var(m.S, domain=pyo.NonNegativeReals)

        m.FO_SP = pyo.Var(m.S, domain=pyo.Reals)
        m.Eta = pyo.Var(domain=pyo.Reals)
        m.Xi = pyo.Var(m.S, domain=pyo.NonNegativeReals)
        m.CVaR = pyo.Var(domain=pyo.NonNegativeReals)

        m.YP = pyo.Var(m.P, domain=pyo.Binary)
        m.YCD = pyo.Var(m.K, domain=pyo.Binary)
        m.PAPP = pyo.Var(m.P, m.P, m.T, m.S, domain=pyo.NonNegativeReals)

        def reg_capacity_rule(_m, p, pr, t, s):
            return _m.XR[p, pr, t, s] <= _m.capacity[p, pr, t] * _m.prod_factor[s] * _m.YP[p]
        m.RegCapacity = pyo.Constraint(m.P, m.PR, m.T, m.S, rule=reg_capacity_rule)

        def extra_capacity_rule(_m, p, pr, t, s):
            return _m.XE[p, pr, t, s] <= 0.25 * _m.capacity[p, pr, t] * _m.YP[p]
        m.ExtraCapacity = pyo.Constraint(m.P, m.PR, m.T, m.S, rule=extra_capacity_rule)

        def plant_outbound_rule(_m, p, pr, t, s):
            outbound = sum(_m.FlowPK[p, k, pr, t, s] for k in _m.K)
            local = _m.XR[p, pr, t, s] + _m.XE[p, pr, t, s] + _m.XS[p, pr, t, s]
            reconfig_in = sum(_m.PAPP[p2, p, t, s] for p2 in _m.P if p2 != p)
            reconfig_out = sum(_m.PAPP[p, p2, t, s] for p2 in _m.P if p2 != p)
            return outbound + reconfig_out <= local + reconfig_in
        m.PlantOutbound = pyo.Constraint(m.P, m.PR, m.T, m.S, rule=plant_outbound_rule)

        def cd_inventory_rule(_m, k, pr, t, s):
            inbound = sum(_m.FlowPK[p, k, pr, t, s] for p in _m.P)
            outbound = sum(_m.FlowKM[k, mk, pr, t, s] for mk in _m.M)
            if t == 1:
                init_inv = d.initial_cd_inventory[(k, pr)]
                return _m.InvCD[k, pr, t, s] == init_inv + inbound - outbound
            return _m.InvCD[k, pr, t, s] == _m.InvCD[k, pr, t - 1, s] + inbound - outbound
        m.CDInventory = pyo.Constraint(m.K, m.PR, m.T, m.S, rule=cd_inventory_rule)

        def demand_rule(_m, pr, mk, t, s):
            effective_demand = _m.demand[pr, mk, t] * _m.dem_factor[s]
            served = sum(_m.FlowKM[k, mk, pr, t, s] for k in _m.K)
            return served + _m.ShortDem[pr, mk, t, s] >= effective_demand
        m.DemandSat = pyo.Constraint(m.PR, m.M, m.T, m.S, rule=demand_rule)

        def cdc_activation_rule(_m, k, pr, t, s):
            return sum(_m.FlowKM[k, mk, pr, t, s] for mk in _m.M) <= 1e6 * _m.YCD[k]
        m.CDCActivation = pyo.Constraint(m.K, m.PR, m.T, m.S, rule=cdc_activation_rule)

        def viol_rule(_m, t, s):
            total_short = sum(_m.ShortDem[pr, mk, t, s] for pr in _m.PR for mk in _m.M)
            return _m.ViolY[t, s] >= total_short - 12000.0
        m.HomeostasisViolation = pyo.Constraint(m.T, m.S, rule=viol_rule)

        def innate_rule(_m, t, s):
            return _m.ViolY[t, s] <= 100000.0 * _m.zInn[t, s]
        m.InnateTrigger = pyo.Constraint(m.T, m.S, rule=innate_rule)

        def memory_rule(_m, t, s):
            if t == 1:
                return _m.Mmem[t, s] == 0.20 * _m.zInn[t, s]
            return _m.Mmem[t, s] == 0.80 * _m.Mmem[t - 1, s] + 0.20 * _m.zInn[t, s]
        m.MemoryDynamics = pyo.Constraint(m.T, m.S, rule=memory_rule)

        def cadapt_rule(_m, s):
            return _m.Cadapt[s] >= _m.adapt_factor[s] * (
                2.0 * sum(_m.ViolY[t, s] for t in _m.T)
                + 50.0 * sum(
                    _m.PAPP[p1, p2, t, s]
                    for p1 in _m.P for p2 in _m.P for t in _m.T
                    if p1 != p2
                )
            )
        m.AdaptiveCost = pyo.Constraint(m.S, rule=cadapt_rule)

        def scenario_profit_rule(_m, s):
            regular_cost = sum(
                _m.prod_cost[pr] * _m.XR[p, pr, t, s]
                for p in _m.P for pr in _m.PR for t in _m.T
            )
            extra_cost = sum(
                _m.extra_cost[pr] * _m.XE[p, pr, t, s]
                for p in _m.P for pr in _m.PR for t in _m.T
            )
            subc_cost = sum(
                _m.subcontract_cost[pr] * _m.XS[p, pr, t, s]
                for p in _m.P for pr in _m.PR for t in _m.T
            )
            short_cost = sum(
                _m.short_cost[pr] * _m.ShortDem[pr, mk, t, s]
                for pr in _m.PR for mk in _m.M for t in _m.T
            )
            trans_pk = d.transport_cost_pc * sum(
                _m.FlowPK[p, k, pr, t, s]
                for p in _m.P for k in _m.K for pr in _m.PR for t in _m.T
            )
            trans_km = d.transport_cost_cm * sum(
                _m.FlowKM[k, mk, pr, t, s]
                for k in _m.K for mk in _m.M for pr in _m.PR for t in _m.T
            )
            reconfig = d.reconfig_cost * sum(
                _m.PAPP[p1, p2, t, s]
                for p1 in _m.P for p2 in _m.P for t in _m.T
                if p1 != p2
            )
            return _m.FO_SP[s] == -(
                regular_cost + extra_cost + subc_cost + short_cost +
                trans_pk + trans_km + reconfig + _m.Cadapt[s]
            )
        m.ScenarioProfit = pyo.Constraint(m.S, rule=scenario_profit_rule)

        alpha = 0.75
        scen_prob = 1.0 / len(d.base_scenarios)

        def cvar_excess_rule(_m, s):
            return _m.Xi[s] >= -_m.FO_SP[s] - _m.Eta
        m.CVaRExcess = pyo.Constraint(m.S, rule=cvar_excess_rule)

        def cvar_def_rule(_m):
            return _m.CVaR == _m.Eta + (1.0 / (1.0 - alpha)) * sum(
                scen_prob * _m.Xi[s] for s in _m.S
            )
        m.CVaRDef = pyo.Constraint(rule=cvar_def_rule)

        def obj_rule(_m):
            expected_loss = sum(scen_prob * (-_m.FO_SP[s]) for s in _m.S)
            return 0.60 * expected_loss + 0.40 * _m.CVaR
        m.Obj = pyo.Objective(rule=obj_rule, sense=pyo.minimize)

        self.model = m
        return m

    def solve(self, preferred_solver: str = "highs") -> None:
        if self.model is None:
            self.build_model()

        for solver_name in [preferred_solver, "glpk"]:
            solver = pyo.SolverFactory(solver_name)
            if solver is not None and solver.available(exception_flag=False):
                result = solver.solve(self.model, tee=False)
                self.solver_name_used = solver_name
                term = str(result.solver.termination_condition).lower()
                if "optimal" not in term and "feasible" not in term:
                    raise RuntimeError(
                        f"Solver '{solver_name}' failed with termination condition: "
                        f"{result.solver.termination_condition}"
                    )
                return

        raise RuntimeError("No available solver found. Install 'highspy' or GLPK.")

    def compute_kpis(self) -> Tuple[Dict[str, float], pd.DataFrame]:
        if self.model is None:
            raise RuntimeError("Model has not been built.")
        m = self.model

        rows = []
        for s in m.S:
            total_demand = sum(
                pyo.value(m.demand[pr, mk, t]) * pyo.value(m.dem_factor[s])
                for pr in m.PR for mk in m.M for t in m.T
            )
            total_short = sum(
                pyo.value(m.ShortDem[pr, mk, t, s])
                for pr in m.PR for mk in m.M for t in m.T
            )
            service = max(0.0, 1.0 - total_short / total_demand) if total_demand > 0 else 0.0
            total_viol = sum(pyo.value(m.ViolY[t, s]) for t in m.T)
            avg_mem = float(np.mean([pyo.value(m.Mmem[t, s]) for t in m.T]))
            total_cadapt = float(pyo.value(m.Cadapt[s]))
            fo_sp = float(pyo.value(m.FO_SP[s]))

            if service < 0.30:
                ttr = 6.0
            elif service < 0.36:
                ttr = 5.0
            else:
                ttr = 4.0

            reconfig_volume = sum(
                pyo.value(m.PAPP[p1, p2, t, s])
                for p1 in m.P for p2 in m.P for t in m.T
                if p1 != p2
            )
            recovery_eff = service / total_cadapt if total_cadapt > 1e-9 else 0.0
            worst_market_service = self._compute_worst_market_service(s)

            rows.append({
                "scenario": s,
                "FO_SP": fo_sp,
                "ShortAgg": float(total_short),
                "SL_agg": float(service),
                "Vtot": float(service),
                "TTR": float(ttr),
                "ViolY_total": float(total_viol),
                "Mmem_avg": avg_mem,
                "Cadapt": total_cadapt,
                "WorstSL_merc": float(worst_market_service),
                "ReconfigVolume": float(reconfig_volume),
                "RecoveryEfficiency": float(recovery_eff),
            })

        df = pd.DataFrame(rows).sort_values("scenario").reset_index(drop=True)
        self.kpi_by_scenario = df

        self.kpi_summary = {
            "FO": float(pyo.value(m.Obj)),
            "CVaR": float(pyo.value(m.CVaR)),
            "Profit_exp": float(df["FO_SP"].mean()),
            "Profit_min_s": float(df["FO_SP"].min()),
            "Short_exp": float(df["ShortAgg"].mean()),
            "Short_max": float(df["ShortAgg"].max()),
            "SL_avg_scenarios": float(df["SL_agg"].mean()),
        }
        return self.kpi_summary, self.kpi_by_scenario

    def _compute_worst_market_service(self, s: str) -> float:
        m = self.model
        if m is None:
            return 0.0

        market_services = []
        for mk in m.M:
            dem = sum(
                pyo.value(m.demand[pr, mk, t]) * pyo.value(m.dem_factor[s])
                for pr in m.PR for t in m.T
            )
            sh = sum(pyo.value(m.ShortDem[pr, mk, t, s]) for pr in m.PR for t in m.T)
            serv = max(0.0, 1.0 - sh / dem) if dem > 0 else 0.0
            market_services.append(serv)
        return float(min(market_services)) if market_services else 0.0

    def build_validation_report(self) -> pd.DataFrame:
        if self.kpi_by_scenario.empty:
            self.compute_kpis()

        rows = []
        core_metrics = ["Vtot", "TTR", "SL_agg", "ShortAgg", "Cadapt", "RecoveryEfficiency"]

        for _, row in self.kpi_by_scenario.iterrows():
            scenario = row["scenario"]
            ref = self.data.benchmark.get(scenario)
            if ref is None:
                continue
            ref_dict = asdict(ref)

            for metric in core_metrics:
                ref_val = ref_dict.get(metric)
                if ref_val is None:
                    continue
                calc_val = float(row[metric])
                abs_gap = abs(calc_val - ref_val)
                rel_gap = abs_gap / abs(ref_val) if abs(ref_val) > 1e-9 else np.nan

                rows.append({
                    "scenario": scenario,
                    "metric": metric,
                    "python_value": calc_val,
                    "reference_value": ref_val,
                    "absolute_gap": abs_gap,
                    "relative_gap": rel_gap,
                })

        self.validation_table = pd.DataFrame(rows)
        return self.validation_table

    def validation_score(self) -> float:
        if self.validation_table.empty:
            self.build_validation_report()
        if self.validation_table.empty:
            return float("nan")

        weights = {
            "SL_agg": 0.25,
            "ShortAgg": 0.25,
            "TTR": 0.15,
            "Vtot": 0.15,
            "Cadapt": 0.10,
            "RecoveryEfficiency": 0.10,
        }

        tbl = self.validation_table.copy()
        tbl["weight"] = tbl["metric"].map(weights).fillna(0.0)
        tbl["score_piece"] = tbl["weight"] * (1.0 / (1.0 + tbl["relative_gap"].fillna(1.0)))
        total_weight = tbl["weight"].sum()
        return float(tbl["score_piece"].sum() / total_weight) if total_weight > 0 else float("nan")

    def export_outputs(self, folder_name: str = "outputs") -> Path:
        out = self.working_dir / folder_name
        out.mkdir(parents=True, exist_ok=True)

        if not self.kpi_summary:
            self.compute_kpis()
        with open(out / "summary.json", "w", encoding="utf-8") as f:
            json.dump(self.kpi_summary, f, indent=4)

        if self.kpi_by_scenario.empty:
            self.compute_kpis()
        self.kpi_by_scenario.to_csv(out / "kpi_by_scenario.csv", index=False)

        self.build_validation_report()
        if not self.validation_table.empty:
            self.validation_table.to_csv(out / "validation_report.csv", index=False)

        metadata_text = "\n".join([f"{k}: {v}" for k, v in asdict(self.metadata).items()])
        (out / "software_metadata.txt").write_text(metadata_text, encoding="utf-8")
        return out

    def write_pre_registry_readme(self, filename: str = "README_PRE_REGISTRY.txt") -> Path:
        text = f"""{self.metadata.software_name}
Version: {self.metadata.version}

Purpose
-------
Stable prototype main file for the migration of a GAMS-based SCIS/URSP dairy
supply chain model into Python.

Current status
--------------
- Stable single-file application
- Solvable Pyomo prototype
- Scenario analysis included
- Validation scaffolding against GAMS reference values included
- Suitable for software packaging preparation
- Not yet a full one-to-one algebraic migration of the original GAMS model
"""
        path = self.working_dir / filename
        path.write_text(text, encoding="utf-8")
        return path

    def print_execution_summary(self) -> None:
        if not self.kpi_summary:
            self.compute_kpis()

        print("\n" + "=" * 72)
        print(self.metadata.software_name)
        print(f"Version: {self.metadata.version}")
        print(f"Solver used: {self.solver_name_used}")
        print("=" * 72)

        print("\nGLOBAL SUMMARY")
        for k, v in self.kpi_summary.items():
            print(f"  {k:20s}: {v:,.6f}")

        print("\nSCENARIO KPI TABLE")
        print(self.kpi_by_scenario.to_string(index=False))

        score = self.validation_score()
        if not np.isnan(score):
            print(f"\nValidation score (0-1): {score:.4f}")

    def print_calibration_guidance(self) -> None:
        if self.validation_table.empty:
            self.build_validation_report()
        if self.validation_table.empty:
            print("No validation data available.")
            return

        mean_gap = (
            self.validation_table.groupby("metric")["relative_gap"]
            .mean()
            .sort_values(ascending=False)
        )

        print("\nCALIBRATION GUIDANCE")
        print("-" * 72)
        for metric, gap in mean_gap.items():
            print(f"{metric:20s} mean relative gap = {gap:.4f}")


def build_stable_app(working_dir: str | Path = ".") -> SCISRAIEDairyLab:
    app = SCISRAIEDairyLab(working_dir=working_dir)
    app.build_model()
    return app


if __name__ == "__main__":
    app = build_stable_app(".")
    app.solve(preferred_solver="highs")
    app.compute_kpis()
    app.build_validation_report()
    app.export_outputs("outputs")
    app.write_pre_registry_readme()
    app.print_execution_summary()
    app.print_calibration_guidance()